### ISSUE TITLE
Update to the latest version of Rebus and .net

### ISSUE THREAD

**Issue by bencz** [rebus-org/Rebus.SignalR#13]
I'm studying the project, I would like to know about the project update to the latest Rebus releases

- Rebus.RabbitMq version 7.4.2
- Rebus.ServiceProvider 8.1.0

I did a test here, I just changed the .net version from 3.1 to 6 and did a complete nuget update on all projects.
I just got a error on this line:

`app.ApplicationServices.UseRebus();`
`  Startup.cs(60, 37): [CS1061] 'IServiceProvider' does not contain a definition for 'UseRebus' and no accessible extension method 'UseRebus' accepting a first argument of type 'IServiceProvider' could be found (are you missing a using directive or an assembly reference?)`

What would be the fix?

**Comment by mookid8000** [comment]
Since you're using Microsoft's generic host(*), you should simply remove the line

```csharp
app.ApplicationServices.UseRebus();
```

because it's no longer necessary – the bus will start/stop at the right times, using an [`IHostedService`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.ihostedservice?view=dotnet-plat-ext-6.0) to manage the bus' lifecycle.

Rebus.ServiceProvider has had even tighter integration with Microsoft DI and the generic host since version 8, which made the `UseRebus(..)` thing unnecessary.

---
(*) I got that from the looks of the line `app.ApplicationServices.UseRebus()`, where I assume `app` is your `IApplicationBuilder`
